#   ____                               __  __   ____   _____                _
#  / ___|  __ _  _ __ ___    ___  ___ |  \/  | / ___| |_   _|  ___    ___  | | ___
# | |  _  / _` || '_ ` _ \  / _ \/ __|| |\/| || |       | |   / _ \  / _ \ | |/ __|
# | |_| || (_| || | | | | ||  __/\__ \| |  | || |___    | |  | (_) || (_) || |\__ \
#  \____| \__,_||_| |_| |_| \___||___/|_|  |_| \____|   |_|   \___/  \___/ |_||___/
#                                                                        by ReferTV
general:
  #Avaliable languages: pl (Polish), en (English), de (German), es (Spanish)
 language: en
 join_listener: true
 quit_listener: true